### ISSUE TITLE
Does `10-5` mean the 5th of October?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#10]
<img width="391" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/1d213e2b-66cc-458e-81e1-f95259f5963d">

However, this panel indicates the metrics are evaluated on the fifth week of October, which is impossible...

**Comment by zhimin-z** [comment]
So basically, you evaluate the metrics consecutively on the first five days of October, is that right? @HLGreener @Bakser @yujifan0326 @shijx12

**Comment by xurh20** [comment]
It used to mean the 5th week of October

**Comment by zhimin-z** [comment]
> It used to mean the 5th week of October

Is that a bit unclear since usually a month has four weeks...?

**Comment by xurh20** [comment]
Yea thats possible, but there's no week level evaluation anymore. Thanks for the reminder though.
