### ISSUE TITLE
What is RTM?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#12]
![image](https://github.com/THU-KEG/KoLA/assets/8592144/0001d3b2-3c37-4037-abbf-358440199405)
![image](https://github.com/THU-KEG/KoLA/assets/8592144/5e672091-420a-4951-94ee-9aeb23bb9867)

**Comment by xurh20** [comment]
RTM refers to Revolving Test of Memorization - As we used E(volving)TM in the paper, we changed the RTM to ETM here.
