### ISSUE TITLE
Is it possible to download the evaluation results as csv or json format?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#13]
I attempt to copy and paste the values, but I found the format is completely wrong on Excel...

**Comment by xurh20** [comment]
Yes, this is supported.

**Comment by zhimin-z** [comment]
> Yes, this is supported.

Where to download it?

**Comment by xurh20** [comment]
![image](https://github.com/THU-KEG/KoLA/assets/90167340/7c6d8bbb-42f2-4cf4-a39a-f65f7a63f4aa)
There's a download json button on the leader board page, by press it you will have the result of that season in a json file.

**Comment by zhimin-z** [comment]
> ![image](https://private-user-images.githubusercontent.com/90167340/315193283-7c6d8bbb-42f2-4cf4-a39a-f65f7a63f4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI5NDIsIm5iZiI6MTcxMTAyMjY0MiwicGF0aCI6Ii85MDE2NzM0MC8zMTUxOTMyODMtN2M2ZDhiYmItNDJmMi00Y2Y0LWEzOWEtZjY1ZjdhNjNmNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTFmNTY1YzM1ZjUxZWVjMGE5ZDVmMzY2Nzc5ZGY0NDZmYzI3YWZmMDhlYjdjYTAxMDdkMDY4YTc5YThkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lniWqCemmEvA1uAWMM6K0GBFKUg1cz94pvGyo5nuBAE) There's a download json button on the leader board page, by press it you will have the result of that season in a json file.

I initial thought that json is the results shown in the panel. However, it is the raw results. Any csv file that showcase the results shown in the panel? I mean, how to retrieve the leaderboard data directly? @xurh20

**Comment by xurh20** [comment]
<img width="259" alt="截屏2024-03-21 23 08 36" src="https://github.com/THU-KEG/KoLA/assets/90167340/cfc7f3d2-027a-4848-9f26-661ef86488be">
<img width="945" alt="截屏2024-03-21 23 09 36" src="https://github.com/THU-KEG/KoLA/assets/90167340/105472d8-e80e-4f5b-88b4-2eaef04d00d7">

Not quite sure what you mean by "raw result". The file has exactly the same score you see on the panel.

**Comment by zhimin-z** [comment]
BTW, where is the URL? It does not appear in the json file @xurh20

**Comment by xurh20** [comment]
I decide not to add that in the json file. I assume its not that relevant if it's the score you wanna retrieve.
