### ISSUE TITLE
The configuration file template is missing in the submission portal...

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#16]
Initially, I selected the [submit option on the leaderboard website](http://103.238.162.37:31622/Submit), followed by clicking on more info, but there was no subsequent response. Similarly, when I attempted to click on the download template file option, I encountered the same lack of response.
![image](https://github.com/THU-KEG/KoLA/assets/8592144/941817f1-977d-4c29-a036-c24b8e9ba218)
After checking, I found both links are unavailable...

**Comment by xurh20** [comment]
We no longer require a submission of a config file, check the up-to-date submit page.

**Comment by zhimin-z** [comment]
> We no longer require a submission of a config file, check the up-to-date submit page.

Thanks for your reply. However, it seems this option is still there...
<img width="600" alt="1710470879213" src="https://github.com/THU-KEG/KoLA/assets/8592144/5438bcfa-dcb1-4fb3-8b8f-d1597e2eb172">

**Comment by xurh20** [comment]
I dont think so? Could u pls double check, thx.

**Comment by zhimin-z** [comment]
> I dont think so? Could u pls double check, thx.

The whole GUI changed! XD
<img width="622" alt="1711037200609" src="https://github.com/THU-KEG/KoLA/assets/8592144/488f7d80-65f2-4fa6-8ab7-983b60ed7b23">

Yeah, that config file is gone now.
