### ISSUE TITLE
The submission functionality does not work now...

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#17]
I attempted to submit the model repository of [Qwen1.5](https://github.com/QwenLM/Qwen1.5) developed by the Qwen team, Alibaba Cloud but found there was no response after clicking on the `submit` button. Even when clicking on the `update` button or refreshing the webpage, the submission button does not function as expected at all...
![image](https://github.com/THU-KEG/KoLA/assets/8592144/17d6c90f-c360-4aa3-b22e-bbee19692ecb)
Check http://103.238.162.37:31622/Submit

**Comment by xurh20** [comment]
Fixed, it works now.
