### ISSUE TITLE
The leaderboards are empty since the beginning of 2024

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#18]
Check http://103.238.162.37:31622/LeaderBoard but found the corresponding leaderboards are empty since the beginning of 2024:
<img width="1211" alt="1709877841595" src="https://github.com/THU-KEG/KoLA/assets/8592144/26ee434f-b182-4398-9862-411ecb0ef599">
<img width="1213" alt="1709877857661" src="https://github.com/THU-KEG/KoLA/assets/8592144/c7d93ff0-00b8-4be5-b555-5963a75b8aa3">
<img width="1226" alt="1709877873201" src="https://github.com/THU-KEG/KoLA/assets/8592144/046deba3-d62c-497f-b63f-466356f14c43">

**Comment by xurh20** [comment]
We will update the S3 data by the end of March 2024(as this is the end of this season)

**Comment by xurh20** [comment]
Hi, just wanna let you know that the s3 result is published on the website, you can have a check if you want, thx!

**Comment by zhimin-z** [comment]
> Hi, just wanna let you know that the s3 result is published on the website, you can have a check if you want, thx!

Thanks so much! It appears over there yet. Closed for now
