### ISSUE TITLE
What does the `update` option intend for?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#19]
Check the submission portal at http://103.238.162.37:31622/Submit, but found `update` option no response after clicking.
<img width="641" alt="1710470965098" src="https://github.com/THU-KEG/KoLA/assets/8592144/c4198059-feb6-4684-8071-7da14e5df69a">
I wonder what this option intend for...

**Comment by xurh20** [comment]
Pls check the latest version, if there's still any issue pls kindly lemme know.
