### ISSUE TITLE
Why are there many duplicate leaderboards?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#2]
<img width="603" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/ce83a6ba-a893-4e8e-abce-a3afa913ba09">

A lot of them are on the same date...

**Comment by xurh20** [comment]
This problem is fixed in current website

**Comment by zhimin-z** [comment]
> This problem is fixed in current website

Why there are still `week` option?
<img width="924" alt="1710470696553" src="https://github.com/THU-KEG/KoLA/assets/8592144/60c3bed7-fcdd-4a7f-9de7-ebe6a55770b7">

**Comment by xurh20** [comment]
<img width="1020" alt="截屏2024-03-21 15 25 41" src="https://github.com/THU-KEG/KoLA/assets/90167340/6fac35a2-5d46-442b-8a89-a16a96a3f014">
Are you checking the latest version? the leaderboard should be fine.

**Comment by zhimin-z** [comment]
> <img alt="截屏2024-03-21 15 25 41" width="1020" src="https://private-user-images.githubusercontent.com/90167340/315192007-6fac35a2-5d46-442b-8a89-a16a96a3f014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjI4MDUsIm5iZiI6MTcxMTAyMjUwNSwicGF0aCI6Ii85MDE2NzM0MC8zMTUxOTIwMDctNmZhYzM1YTItNWQ0Ni00NDJiLThhODktYTE2YTk2YTNmMDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyMDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNmViY2U2OGI5YzI4MmI1MGRkZjEwYmNmNmI5MzU0N2Y2NTY5ZmM0NjczYzEzY2RjODE2ZTJmNjc3OGQ0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SIsLwGqsL9axoiIF5ZtdfIZ7uVZJggZ2L9PN5nJKNYs"> Are you checking the latest version? the leaderboard should be fine.

It indeed gets updated recently, great!
