### ISSUE TITLE
All those metrics of leaderboard based on week are the same when selecting the same season

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#3]
<img width="929" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/bfff03e7-8450-4330-a702-a92a256ce65e">

That indicates the redundancy of the existing leaderboard, maybe it is recommended to conduct the evaluation not that frequently? @HLGreener @Bakser @yujifan0326 @shijx12

**Comment by xurh20** [comment]
We no longer support week level query(and test) and currently you can only access model score data of different seasons
