### ISSUE TITLE
The season and week correspondence is messed up

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#4]
<img width="433" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/042c91a6-e381-4f38-85dc-a661f6d5f170">
<img width="415" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/26b51115-1224-4bf5-837e-541f4f588493">

They seem to overlap and contradict each other...I have no clue how to use it correctly.

**Comment by zhimin-z** [comment]
For example, when I select `S1` and `S5` together, then it is no responding...
<img width="917" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/86087d8f-3a06-4c96-a17e-2659510eeb9b">

**Comment by xurh20** [comment]
see the newest version, no more weeks

**Comment by zhimin-z** [comment]
> see the newest version, no more weeks

Thanks, but clicking on the week option fails to update the existing leaderboards, anything went wrong?
<img width="610" alt="1710470585927" src="https://github.com/THU-KEG/KoLA/assets/8592144/f5f5fa38-3301-4701-82da-afc5197e2bcc">

**Comment by xurh20** [comment]
Please check the web's latest version, thx!
