### ISSUE TITLE
Why do you regard a month as a season?

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#5]
<img width="424" alt="image" src="https://github.com/THU-KEG/KoLA/assets/8592144/be2bc231-eb6e-4944-b948-923216fa1345">

It seems every month to be regarded as a unique season...and the evaluations are duplicate in a monthly basis...This does not make good sense...

**Comment by xurh20** [comment]
no we regard 3 months as a season

**Comment by zhimin-z** [comment]
> no we regard 3 months as a season

But there are three seasons sharing the same month...For example, there are three `S1` seasons, with each spanning across the entire June (2023-6-01-2023-6-30).

Anyway, since the whole leaderboard system gets updated recently, I would close this issue tracker for now.
