### ISSUE TITLE
Unable to log into the website with GitHub authentication

### ISSUE THREAD

**Issue by zhimin-z** [THU-KEG/KoLA#9]
![image](https://github.com/THU-KEG/KoLA/assets/8592144/e68979e1-5bf2-45cc-9d47-86deeec02d00)

**Comment by zhimin-z** [comment]
Now there is no jump after clicking login button...

**Comment by xurh20** [comment]
We only keep the submission function now for people to submit their model to be tested on this benchmark, login is no longer supported.

**Comment by zhimin-z** [comment]
> We only keep the submission function now for people to submit their model to be tested on this benchmark, login is no longer supported.

But how to check the submission/evaluation history if we cannot log into our account XD?

**Comment by xurh20** [comment]
Currently, you can check the evaluation result on the leaderboard page for each season, and we will support per model result soon, there's no need to have an account for that. As long as you submit your model through the submission page, we will include your model in the next season's test.

**Comment by zhimin-z** [comment]
Closed since login button is permanently removed from the leaderboard now :)
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/506725bd-237e-438b-bf39-da194d3877e9">
